### ISSUE TITLE
Ctrl+Shift+B is hijacked by booklight

### ISSUE THREAD

**Issue by captn3m0** [ahmadassaf/booklight#10]
The command is supposed to hide/show the bookmark bar, but booklight hijacks the shortcut (Note that it is fine for booklight to take Ctrl+B).

OS: Ubuntu 14.04
Chrome: 42.0.2311.4 (Official Build) dev (64-bit)

The shortcut works on new tab page, where booklight isn't loaded, but stops working on other pages.

**Comment by ahmadassaf** [comment]
Thanks for spotting this. Fixed in the latest version on Github and version 2.1 on Chrome store
