### ISSUE TITLE
Add a way to search for and launch bookmarks

### ISSUE THREAD

**Issue by mwagstaff** [ahmadassaf/booklight#16]
Unless I'm missing something (very possible), the only functionality offered is to add bookmarks. It would be great if we could use the same (excellent) search interface to launch bookmarks as well. :)

**Comment by ahmadassaf** [comment]
Hello @mwagstaff Actually you can, please let me know if it was not clear in the documentation. But by pressing the `space` bar after launching booklight, you will be taken into an interface to search on bookmarks. 
Please let me know if it works for you.

**Comment by mwagstaff** [comment]
Ah, I should have read the docs more carefully. Maybe you could make it a bit more obvious by adding a note near the top, just under where you say "To Launch press (ctrl/Control + b) and thats it"?

Very nice, though. Loving it even more now. Thanks for your work, and the quick response!

**Comment by ahmadassaf** [comment]
Fixed :+1:  Thanks a lot for your feedback.

I am really glad you liked the idea :)
