### ISSUE TITLE
Remembering last used folder when multiple tabs are open

### ISSUE THREAD

**Issue by jpeg729** [ahmadassaf/booklight#17]
Here is what I often do.
1. Open loads of tabs on a theme
2. Browse and close some
3. Bookmark some of the ones still open in the same folder

But booklight doesn't seem to remember the folder I last used. I'm not sure whether reloading the page is enough, or whether I actually have to reload the browser.

I know I could use the bookmark all tabs in a new folder function - but there are tons of situations where that isn't appropriate.

**Comment by ahmadassaf** [comment]
I see what you mean. I know why this is happening. Let me do some performance hecks (the problem is with caching the request).

I'll ping you with updates soon. 

Thanks for your feedback

**Comment by ahmadassaf** [comment]
Actually this is the same issue as #5
