### ISSUE TITLE
Feature request: Open bookmark

### ISSUE THREAD

**Issue by solcik** [ahmadassaf/booklight#3]
I would very welcome option to find bookmarks them selfs and open them..
I will try to look in this (if it is even possible) ASAP I will have time.

**Comment by ahmadassaf** [comment]
@solcik thanks for the suggestion .. it is on my to-do list for sure. I am already fetching the normal bookmarks as well. I was thinking of how to enable search of them, a possible way is to to hit space and then it will search on bookmarks immediately

**Comment by ahmadassaf** [comment]
the new version can now search and open bookmarks (in current window and in a new tab)
