### ISSUE TITLE
Bookmark filter match parttern  problem 

### ISSUE THREAD

**Issue by snsnsjsn** [ahmadassaf/booklight#30]
there is sentence and some word could match , and some could not .
just like this 
![image](https://user-images.githubusercontent.com/11435527/67768575-cdb47800-fa8d-11e9-92da-98d3fb8b2d1b.png)

**Comment by ahmadassaf** [comment]
Could not reproduce.

Also, this depends on the Full-Text search implementation of the JS library used, you might need to add more letters to filter properly.
