### ISSUE TITLE
Booklight screws up with Font Awesome 3.2.1

### ISSUE THREAD

**Issue by captn3m0** [ahmadassaf/booklight#7]
Font Awesome 3.2.1

Booklight enabled:
![image](https://cloud.githubusercontent.com/assets/584253/6486374/7d51a7ee-c2b0-11e4-9aca-e53df1052d0b.png)

Booklight disabled:
![image](https://cloud.githubusercontent.com/assets/584253/6486381/8ad970ea-c2b0-11e4-9c94-fdb4a5313fed.png)

You can test it on the old 3.2.1 docs: https://fortawesome.github.io/Font-Awesome/3.2.1/

At first I thought it was because of my [disable-web-fonts](https://github.com/captn3m0/disable-web-fonts) extension, but that was turned off. Its definitely booklight's fault.

**Comment by ahmadassaf** [comment]
my bad .. i've just fixed the issue. I was using fontello and the two did not play nicely together. I am pushing a new version now to the chrome store and it should be updated within the next 60 mins. Thanks for spotting this :)
