### ISSUE TITLE
The enter key is overridden (critical bug)

### ISSUE THREAD

**Issue by p3lim** [ahmadassaf/booklight#9]
No matter if the bookmarking frame is open or not, the enter key is occupied by this extension, which means I can't use it anywhere else in a webpage.

**Comment by ahmadassaf** [comment]
thanks for spotting this, i did change the library that handles listening to keystrokes. I noticed before that sometime bookmark were added when pressing enter outside of the booklight frame. I've just fixed this, pushed the new code and updated the extension in the chrome store (should reflect in 60 minutes).
